name = "no-bool-switch"
description = "Don't switch on boolean values, use if instead"
query = """
(switch_exp
  (case [
    (lit_pat (bool_literal))
    (tup_pat . (lit_pat (bool_literal)) @trailing)
  ])) @error
"""
