name = "prefer-field-punning"
description = "Use field punning to avoid repetition. Replace { field = field } with { field }"
query = """
(
  (exp_field
    (identifier) @field
    (var_exp (identifier) @value)
  ) @error
  (#eq? @field @value)
)
"""
