name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        shell: bash
        run: bun i --frozen-lockfile

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "auto"

      - name: Setup Mops
        uses: dfinity/setup-mops@v1

      - name: Install Mops Packages
        run: mops install

      - name: Build
        run: |
          dfx start --background
          dfx deploy
          dfx stop

      - name: Check Format
        run: bun run format:check

      - name: Lint Motoko
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/caffeinelabs/lintoko/releases/download/v0.7.0/lintoko-installer.sh | sh
          ./lintoko -r .lintoko src

      - name: Test
        run: bun run test
